# Generated by Django 3.1.7 on 2021-04-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('job', models.CharField(max_length=250)),
                ('teacher_text', models.CharField(max_length=250)),
            ],
        ),
    ]
